name: Testing Azure Login Action

on:
  workflow_dispatch:

jobs:
  build:
    name: Testing Azure Login Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
